### ISSUE TITLE
Amount of skill points shown isn't working right

### ISSUE THREAD

**Issue by Shahelion** [Vazkii/Skillable#14]
When opening the interface, it always shows that I have 0 skill points, no matter how many I actually have. Upon spending a skill point, it then says I have 1 point left, again regardless of the actual amount. It continues to say 1 even after spending all available points until the interface is closed and re-opened, which sets it back to 0.

Basically, I have no idea at any given time how many points I actually have, or even if I have any (still not sure how to even get them, but that's aside).

**Comment by Vazkii** [comment]
I can't reproduce this.

**Comment by Shahelion** [comment]
So, I finally realized I was reading it completely wrong. So, no actual issue. Woops.
