### ISSUE TITLE
roadwalk trait damages player

### ISSUE THREAD

**Issue by ilvrak** [Vazkii/Skillable#15]
"Roadwalk" trait do not increase speed, but when i walk forward on "grass path" pulls me up-down and does damage

Skillable-beta-9
forge 2557

**Comment by Dawenzel** [comment]
I don't know if this helps at all, but I also found this issue in an instance running:

- Forge 14.23.0.2544
- AutoRegLib 1.3-15
- Skillable beta-8

Like @ilvrak stated the trait makes the player "jump" repeatedly while walking on a grass path and when the player gets off the path it takes damage. The amount of damage gets higher the further the player walks on the path.
