### ISSUE TITLE
[Enhancement] Level Tweaks

### ISSUE THREAD

**Issue by Silvrus** [Vazkii/Skillable#3]
Hello, I've found Skillable to be a great mod, thank you for making it. I was thinking about the progression in it though. Normally using general XP to unlock abilities is perfectly fine, but in hardcore packs that may not be completely feasible. I know what I'm asking is probably really intensive, but I was wondering if instead of using general XP, which is gained through limited means, rather the skills level up by use, i.e. killing mobs levels attack, taking damage levels defense or mining levels mining?

**Comment by Vazkii** [comment]
That was the original plan, however, it isn't feasible to track which blocks are placed by the player and which came with the world, so the idea can't be properly implemented.
