### ISSUE TITLE
Skillable cause some mod block interactions to fail

### ISSUE THREAD

**Issue by leagris** [Vazkii/Skillable#4]
Even when levels and achievement requirements are met.
Quark chests remains visually open after usage.
Techreborn tools (stone cutter, drill…) can not break blocks.
There are possibly other hiccups with other mods interaction. Those two above for sure.

**Comment by b0bst3r** [comment]
Add Futurepacks Wardrobes too, more alarming is it opens the GUI (after being locked) and allows you to place items inside the wardrobes when items exist (but you can't see because it's locked).  What happens to these items or the items inside when it becomes unlocked, not tested this yet.

**Comment by darkshadow543** [comment]
Fake players cannot use tools that would be locked to a beginning player.  For instance, putting a diamond pickaxe in a mechanical user from extra utilities will not work as a block breaker, when it should, also prevents bonemealing to when using said mechanical user.

**Comment by Vazkii** [comment]
Can't reproduce the quark one, but I'll add a config to not enforce fake players.
