### ISSUE TITLE
[Request][1.12] Option to give player configurable amount of xp after unlocking an Advancement

### ISSUE THREAD

**Issue by Alaberti** [Vazkii/Skillable#9]
Is this something that could fall into Skillable's purview? Several players on my server have commented that it would be a useful addition to have. Please and thank you.

**Comment by Vazkii** [comment]
I believe vanilla advancements have this feature built in by default.

**Comment by Alaberti** [comment]
Ah, it's a bit tricky but it's there. Time to edit some data files; thanks for the tip
